[package]
authors = ["Konstantin Bedritskiy <vigdail.dev@gmail.com>"]
edition = "2018"
name = "kata"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1.3.9"
